global:
  resolve_timeout: 2m

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: [ 'alertname', 'service' ]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 5h
  receiver: email

  routes:
    - receiver: 'email'
      matchers:
        - severity=info|warning

    - receiver: 'telegram'
      matchers:
        - severity=critical

receivers:
  - name: 'email'
    email_configs:
      - to: ${MAIL_RECEIVER}
        from: ${MAIL_SENDER}
        smarthost: ${MAIL_HOST}
        auth_username: ${MAIL_USERNAME}
        auth_password: ${MAIL_PASSWORD}
        send_resolved: true

  - name: 'telegram'
    telegram_configs:
      - bot_token: ${TELEGRAM_BOT_TOKEN}
        chat_id: ${TELEGRAM_CHAT_ID}
        send_resolved: true