services:
  elasticsearch-exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter
    container_name: anilibrary-elasticsearch-exporter
    command:
      - '--es.uri=${ELASTICSEARCH_URL}'
    ports:
      - ${ELASTICSEARCH_EXPORTER_PORT}:9114
    networks:
      - shared

networks:
  shared:
    name: anilibrary
    external: true