version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    container_name: anilibrary-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1
      interval: 2s
      timeout: 2s
      retries: 5
    networks:
      - local
      - shared

  alertmanager:
    image: prom/alertmanager
    container_name: anilibrary-alertmanager
    profiles:
      - alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - local

  grafana:
    image: grafana/grafana
    depends_on:
      prometheus:
        condition: service_healthy
    container_name: anilibrary-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SECURITY_ALLOW_SING_UP=false
    ports:
      - "3005:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - local

  jaeger:
    image: jaegertracing/all-in-one
    container_name: anilibrary-jaeger
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:14269 || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14269:14269"
      - "9412:9412"
    networks:
      - local
      - shared

volumes:
  grafana-data:
  prometheus-data:

networks:
  local:
    driver: bridge
  shared:
    name: anilibrary
    external: true