rule_files:
  - 'alerts/*.yml'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: "scraper_metrics"
    scrape_interval: 10s
    static_configs:
      - targets: [ 'anilibrary-scraper:8081' ]

  - job_name: 'tempo'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'elasticsearch-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: [ 'elasticsearch-exporter:9114' ]