apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    access: proxy
    url: http://anilibrary-prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true