{
 "title": "Scraper metrics",
 "description": "Detailed metrics for Scraper.",
 "tags": [
  "go",
  "metrics",
  "scraper"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Scraper requests",
   "type": "bargauge",
   "description": "View total and failed requests to Scraper.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scraper_requests_counter", "legendFormat": "Requests" },
    {
     "expr": "scraper_failed_requests_counter",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "Scraper cache",
   "type": "timeseries",
   "description": "View Scraper cache hits and misses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "cache_hits_counter", "legendFormat": "Cache hit" },
    { "expr": "cache_misses_counter", "legendFormat": "Cache miss" }
   ]
  },
  {
   "title": "Scraper panic counter",
   "type": "gauge",
   "description": "Counter of all panics that occurred in Scraper.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "panics_counter", "legendFormat": "Panic counter" }
   ]
  }
 ]
}